# Generated by Django 5.0.2 on 2024-02-27 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_singletonmodel_delete_systemstatusdocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstatus',
            name='window',
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='blinds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='doorLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='windowOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='fan',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='lights',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='securityArmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='securityBreached',
            field=models.BooleanField(default=False),
        ),
    ]
