# Generated by Django 5.0.2 on 2024-02-27 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_systemstatus_window_systemstatus_blinds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='humidity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='temperature',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
