# Generated by Django 5.0.2 on 2024-02-27 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_systemstatus_humidity_systemstatus_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='humidity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
