# Generated by Django 5.0.2 on 2024-03-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_systemstatus_humidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstatus',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='lights',
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='fanOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='lightsOn',
            field=models.BooleanField(default=False),
        ),
    ]
